pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO = 'etl-docker-repo'
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS = credentials('AWS_SECRET_ACCESS')
        IMAGE_TAG = 'latest'
        LAMBDA_FUNCTION_NAME = 'elt_lambda'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-credentials', url: 'https://github.com/junaida31311/MainAnalytics.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t $ECR_REPO:latest docker/"
                }
            }
        }

        stage('Push to ECR') {
            steps {
                script {
                    sh """
                    aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin us-east-1.dkr.ecr.$AWS_REGION.amazonaws.com
                    docker tag $ECR_REPO:latest us-east-1.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
                    docker push us-east-1.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
                    """
                }
            }
        }

        stage('Deploy with Terraform') {
            steps {
                script {
                    sh """
                    cd terraform
                    terraform init
                    terraform apply -auto-approve
                    """
                }
            }
        }

        stage('Test Lambda') {
            steps {
                script {
                    sh "aws lambda invoke --function-name etl_lambda --payload '{}' response.json"
                }
            }
        }
    }
}